### ISSUE TITLE
Issue with Incorrect Display of SwaggerUI in Extension Update Version 4.25.0

### ISSUE THREAD

**Issue by Dezmont51** [42Crunch/vscode-openapi#264] opened 2024-03-01 14:40 UTC
Following the update to version 4.25.0 of the extension, I've noticed that the SwaggerUI preview displays incorrectly. It seems to be dependent on the size of the OpenAPI file, which contains around 10,000 lines. Removing certain methods appears to resolve the issue. Everything worked fine in the previous version.

v4.24.1
<img width="1444" alt="v4 24 1" src="https://github.com/42Crunch/vscode-openapi/assets/4850928/e5af9c4b-4bab-4589-9cce-891828cbc9b6">
v4.25.0
<img width="1433" alt="v4 25 0 " src="https://github.com/42Crunch/vscode-openapi/assets/4850928/2fe95e48-71f1-4ccd-bcd9-d13c6d414aa5">

**Comment by ak1394** [comment] 2024-03-01 14:50
Thanks for the report. Could you possibly share the openapi file in question? Would it render correctly if you try it with standalone Swagger UI, for example at https://petstore.swagger.io/ ?

**Comment by ak1394** [comment] 2024-03-01 15:14
Also, looking at the lock files I see that `swagger-ui-react` which we use to display the preview, has been updated from 5.11.7 to 5.11.8, maybe this is the cause of the issue.

If sharing the OAS file is not an option for you, I can build a .visx package for you, to try rolling back 5.11.8 to 5.11.7 to see if this fixes the issue.

**Comment by ak1394** [comment] 2024-03-01 15:33
Sure, feel free to email the file to anton.krasovsky@42crunch.com, I'll keep it confidential.

**Comment by ak1394** [comment] 2024-03-01 15:35
Sure, feel free to email the file to anton.krasovsky@42crunch.com, I'll keep it confidential.

**Comment by ak1394** [comment] 2024-03-01 16:31
I've published version 4.25.1 downgrading the Swagger UI version, which should solve your issue.

I'm not sure what exactly is the problem with a newer Swagger UI, and it is likely that in a couple of month time I'll have to upgrade again. 

It might be the best to open an issue with them directly at https://github.com/swagger-api/swagger-ui/issues to make sure this problem is fixed in a future versions.

**Closed** 2024-03-01 17:11 UTC
