### ISSUE TITLE
$ref intellisense inserts unnecessary quotes & text

### ISSUE THREAD

**Issue by Ansis100** [42Crunch/vscode-openapi#210] opened 2023-03-22 10:03 UTC
Hi,
I'm having an issue where $ref is being really annoying. Intellisense autocompletes the component but inserts unnecessary double quotes and doesn't take into account the previous text which needs to be deleted. See below.
This issue only happens with $ref links.

![Peek 2023-03-22 12-00](https://user-images.githubusercontent.com/35926716/226868376-241c79ea-d0fc-43f1-a758-d0109c78de36.gif)

**Comment by Ansis100** [comment] 2023-03-22 10:09
Just tested and found out that the issue doesn't happen if the extension is disabled.

**Comment by ak1394** [comment] 2023-03-22 12:17
Thanks for reporting! Looks like it might be caused by a recent change in in VS Code autocompletion. In any case that's something for us to fix, I'll publish the update soon.

**Comment by ak1394** [comment] 2023-03-22 22:53
Fixed in todays update v4.16.1

**Closed by ak1394** 2023-03-22 22:53 UTC
