### ISSUE TITLE
Wrong warning for pattern rule

### ISSUE THREAD

**Issue by ansidev** [42Crunch/vscode-openapi#29] opened 2019-10-24 19:29 UTC
I have a model:

```
User:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 100
          pattern: /^[\w\s]+$/
          example: John
        lastName:
          type: string
          maxLength: 100
          pattern: /^[\w\s]+$/
          example: Doe
        fullName:
          type: string
          maxLength: 100
          pattern: /^[\w\s]+$/
          example: John Doe
```

The warnings are `The value of the schema example '/components/schemas/User/properties/{firstName, lastName, fullName}/example' is not consistent with the schema`.

**Comment by ak1394** [comment] 2019-10-24 22:17
Thanks for reporting! Could you provide full openapi sample?

**Comment by ak1394** [comment] 2020-07-03 14:24
Can't reproduce, closing.

**Closed by ak1394** 2020-07-03 14:24 UTC
