### ISSUE TITLE
Incorrectly flagging "Missing property "$ref"" for openAPI 3.0.X

### ISSUE THREAD

**Issue by PaddyJM** [42Crunch/vscode-openapi#163] opened 2022-03-07 12:37 UTC
The extension is flagging the error in the title on the "properties" field of the below 

```
openapi: 3.0.1
info:
    version: 1.0.0
    title: Stub Server of the BF Database
    description: Stub Server of the BF Database
paths:
    /client/details:
        get:
            description: Returns the details of the client using the client number in the JWT
            responses:
                "200":
                    description: Returns client details
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: #red flag here
                                    firstName:
                                        type: string
                                        description: The first name of the client
                                        x-faker: name.firstName
                                        example: John
                                    lastName:
                                        type: string
                                        description: The last name of the client
                                        x-faker: name.lastName
                                        example: Smith
                "401":
                    description: Unauthorised
                "404":
                    description: Client not found
                "500":
                    description: An unexpected error occured
```
Based on my understanding, $ref is only for when I wish to create a snippet that I wish to reuse. 

https://swagger.io/docs/specification/using-ref/

But I don't want to do this, so why is flagging? Surely it is not required that I have to reference reusable snippets?

**Comment by ak1394** [comment] 2022-03-07 22:55
@elmeunick9 thanks for finding the issue! Indeed this is a problem caused by a recent YAML extension update (version 1.5.0). For now I suggest to downgrade to a previous version (1.4.0). To do that go to Extensions, find YAML, click on a gear icon and choose "Install Another Version...", select 1.4.0 and then restart VS Code.

**Comment by jerryjeremiah** [comment] 2022-03-09 00:29
Looks like YAML 1.5.1 is out and it fixes this.

**Comment by ak1394** [comment] 2022-03-09 13:14
@jerryjeremiah Thanks for letting us know. I'll close the issue then.

**Closed by ak1394** 2022-03-09 13:14 UTC
