### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by henningeiben** [42Crunch/vscode-openapi#44] opened 2020-03-04 07:41 UTC
When I enable the extension I get the following message:

```
Problems loading reference 'openapi-schemas:openapi-2.0.json': Unable to load schema from 'openapi-schemas:openapi-2.0.json': Request vscode/content failed with message: cannot open openapi-schemas:openapi-2.0.json. Detail: resource is not available.
```

When I disable the extension, OOTB intellisense for swagger in vscode works just fine.

VSCode Version: 1.42.1
OpenAPI (Swagger) Editor Version: 2.1.1

**Comment by ak1394** [comment] 2020-03-19 21:51
This is a duplicate of this issue https://github.com/42Crunch/vscode-openapi/issues/46 which is being investigated.

**Closed by ak1394** 2020-03-19 21:51 UTC
