### ISSUE TITLE
Resolver error when referencing external schema files

### ISSUE THREAD

**Issue by nize** [42Crunch/vscode-openapi#147] opened 2021-10-20 14:31 UTC
I get the following error when rendering an OpenAPI spec using swagger:
`Resolver error at paths./pet.get.responses.200.content.application/json.schema.allOf.1.properties.pets.items.allOf.0.$ref
Could not resolve reference: #/paths/~1pet~1%7BpetId%7D/get/responses/200/content/application~1json/schema/allOf/0`

See [this stackoverflow post](https://stackoverflow.com/questions/69622868/resolver-error-when-referencing-external-schema-files) for a problem description and the code.

The problem is not there when I use ReDoc.

I was about to register the issue at https://github.com/swagger-api/swagger-ui but they state that:
_Issues on GitHub are only related to problems of Swagger-UI itself. We'll try   to offer support here for your use case, but we can't offer help with projects that use Swagger-UI indirectly, like Springfox or swagger-node._

**Comment by ak1394** [comment] 2021-11-03 11:52
Thanks for providing the OpenAPI samples along the issue, I'll try to reproduce it locally and see if we can address it in the extension.

**Comment by ak1394** [comment] 2021-12-06 20:03
It looks like the issue is indeed with SwaggerUI. Our extension supports multi-file OpenAPI files (which Swagger UI does not) so before asking SwaggerUI to render a multi-file OpenAPI we "bundle" multiple files to a single one, resolving refs, etc.

Looking at the example provided, it appears that the bundling step succeeds, and the issue happens at the stage when SwaggerUI attempts to render it.

I'm attaching resulting "bundled" file, which you can use to open issue with SwaggerUI team.

[bundled_json.txt](https://github.com/42Crunch/vscode-openapi/files/7663190/bundled_json.txt)

On the other hand, I suggest that your multi-file OpenAPI file should be simplified.

For instance I would place all schemas to "/components/schemas" (possibly using external $refs) and put references from "response" sections to "/components/schemas/Foo" instead of referring external files directly like here:

"items": {
     "$ref": "pet-lite.schema.json"
}

**Closed by ak1394** 2021-12-06 20:03 UTC
