### ISSUE TITLE
Extension breaks JSON schema validation with array items

### ISSUE THREAD

**Issue by shuebner** [42Crunch/vscode-openapi#272] opened 2024-04-29 09:59 UTC
The extension seems to break VSCode's own JSON schema validation for JSON schemas with item array subschemas.

VSCode version: 1.88.1
OpenAPI extension version: 4.25.3

# Steps to Reproduce:

1. Install/enable the OpenAPI extension
2. Define a JSON schema with array tuple validation:
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": [
        {
            "type": "string"
        },
        {
            "type": "integer"
        }
    ]
}
```
3. Let VSCode validate an invalid file:
```json
[
    42,
    "foo"
]
```

# Actual Behavior:

VSCode does not show any error even though the file is not valid against the schema.

# Expected Behavior

VSCode shows validation errors.

# Steps to show that OpenAPI extension seems to be the problem
1. Disable OpenAPI extension and restart VSCode
2. Observe that VSCode now correctly marks the file as invalid.

**Comment by ak1394** [comment] 2024-04-30 17:25
Thanks for reporting. I think this is vscode issue. I've commented in the related issue.

**Comment by ak1394** [comment] 2024-05-08 21:12
Closing, as the issue is in 'vscode-json-languageservice' not this extension.

**Closed by ak1394** 2024-05-08 21:12 UTC
